export const copy = {
  nav: {
    dashboard: 'Início',
    appointments: 'Agendamentos',
    professionals: 'Profissionais',
    services: 'Serviços',
    hours: 'Horários',
    settings: 'Configurações',
    dashboardHint: 'Resumo do dia',
    appointmentsHint: 'Fluxo e bloqueios',
    professionalsHint: 'Escala e cadastro',
    servicesHint: 'Ofertas e duração',
    hoursHint: 'Jornada da casa',
    settingsHint: 'Marca e integrações',
  },
  common: {
    loading: 'Carregando...',
    save: 'Salvar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    processing: 'Processando...',
    managerAccount: 'Conta administrativa',
    logout: 'Sair do painel',
  },
  confirmModal: {
    eyebrow: 'Confirmação',
  },
  booking: {
    eyebrow: 'Agendamento online',
    service: '1. Serviço',
    professional: '2. Profissional',
    time: '3. Horário',
    customer: '4. Dados',
    confirmation: '5. Confirmação',
    notFoundTitle: 'Não encontrado',
    notFoundMessage: 'Estabelecimento não encontrado.',
    loadingMessage: 'Montando a experiência de agendamento.',
  },
}
